const roles={
  superadmin:{label:'Super Admin',user:'admin',password:'1234',initials:'SA',subtitle:'Full access',nav:[['dashboard','Dashboard','▦'],['fuel','Fuel entry','＋'],['approvals','Approvals','✓'],['customers','Customers','♙'],['reports','Reports','▤'],['access','Access control','◇']],title:'Good evening, Super Admin',note:'Demo access: admin / 1234'},
  manager:{label:'Sales Manager',user:'manager',password:'1234',initials:'SM',subtitle:'Sales & approvals',nav:[['dashboard','Dashboard','▦'],['fuel','Fuel entry','＋'],['approvals','Approvals','✓'],['customers','Customers','♙'],['reports','Reports','▤']],title:'Good evening, Sales Manager',note:'Demo access: manager / 1234'},
  attendant:{label:'Pump Attendant',user:'attendant',password:'1234',initials:'PA',subtitle:'Station operations',nav:[['dashboard','Dashboard','▦'],['fuel','Fuel entry','＋']],title:'Good evening, Pump Attendant',note:'Demo access: attendant / 1234'},
  accountant:{label:'Accountant',user:'accountant',password:'1234',initials:'AC',subtitle:'Finance & reports',nav:[['dashboard','Dashboard','▦'],['approvals','Approvals','✓'],['customers','Customers','♙'],['reports','Reports','▤']],title:'Good evening, Accountant',note:'Demo access: accountant / 1234'},
  dealer:{label:'Dealer',user:'dealer',password:'1234',initials:'DL',subtitle:'Dealer overview',nav:[['dashboard','Dashboard','▦'],['customers','Customers','♙'],['reports','Reports','▤']],title:'Good evening, Dealer',note:'Demo access: dealer / 1234'}
};
const data={sales:[31,55,42,72,49,79,62],days:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'],activities:[['⛽','Diesel · TN15 AB 4582','ABC Transport · ₹8,120','Approved'],['⛽','Petrol · TN32 K 9931','Cash sale · ₹2,400','Paid'],['◫','Tally sync completed','18 vouchers posted','Done']],approvals:[['Fuel issue · TN15 AB 4582','Diesel / 240 L','₹24,000','Pending'],['Credit sale · ABC Transport','Invoice #KA-2480','₹8,120','Pending'],['Shift close · Evening','Pump 03 / 18 entries','₹42,800','Pending'],['Fuel issue · TN32 K 9931','Petrol / 40 L','₹4,200','Approved']]};
let activeRole='superadmin';let activePage='dashboard';
const $=selector=>document.querySelector(selector);
const loginView=$('#loginView'),portalView=$('#portalView'),roleSelect=$('#roleSelect');
Object.entries(roles).forEach(([key,role])=>roleSelect.add(new Option(role.label,key)));
function updateLoginFields(){const role=roles[roleSelect.value];$('#userId').value=role.user;$('#password').value=role.password;$('#demoNote').textContent=role.note}
roleSelect.addEventListener('change',updateLoginFields);
$('#togglePassword').addEventListener('click',()=>{const input=$('#password');const visible=input.type==='text';input.type=visible?'password':'text';$('#togglePassword').textContent=visible?'Show':'Hide'});
$('#loginForm').addEventListener('submit',event=>{event.preventDefault();const role=roles[roleSelect.value];if($('#userId').value!==role.user||$('#password').value!==role.password){showToast('Check the demo credentials for this role.');return}activeRole=roleSelect.value;loginView.classList.add('hidden');portalView.classList.remove('hidden');activePage='dashboard';renderShell();showToast(`Signed in as ${role.label}`)});
function renderShell(){const role=roles[activeRole];$('#profileAvatar').textContent=role.initials;$('#profileName').textContent=role.label;$('#profileRole').textContent=role.subtitle;$('#mainNav').innerHTML=role.nav.map(([id,label,icon])=>`<button class="nav-item ${id===activePage?'active':''}" data-page="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('');document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>{activePage=button.dataset.page;renderShell();$('#sidebar').classList.remove('open')}));renderPage()}
function renderPage(){const role=roles[activeRole];const titles={dashboard:['OPERATIONS / TODAY',role.title,'Live overview across Kallakurichi station activity.'],fuel:['WORKSPACE / FUEL ENTRY','Fuel movement','Capture a sale, issue, or shift movement.'],approvals:['WORKSPACE / APPROVALS','Review queue','Keep the station moving with quick decisions.'],customers:['WORKSPACE / CUSTOMERS','Customers','Credit accounts and transport partners.'],reports:['WORKSPACE / REPORTS','Reports & insights','A live view of performance and reconciliation.'],access:['ADMIN / ACCESS CONTROL','Team permissions','Control who can see and act on agency data.']};const [eyebrow,title,subtitle]=titles[activePage]||titles.dashboard;let html=`<div class="page-heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${subtitle}</p></div><div class="heading-actions">${activePage==='dashboard'||activePage==='fuel'?'<button class="primary-button" id="newEntryButton">+ New fuel entry</button>':''}</div></div>`;if(activePage==='dashboard')html+=dashboardHtml();else if(activePage==='access')html+=accessHtml();else if(activePage==='approvals')html+=approvalsHtml();else if(activePage==='customers')html+=customersHtml();else if(activePage==='reports')html+=reportsHtml();else html+=fuelHtml();$('#mainContent').innerHTML=html;const entryButton=$('#newEntryButton');if(entryButton)entryButton.addEventListener('click',openModal);document.querySelectorAll('.action-approve').forEach(button=>button.addEventListener('click',()=>{button.closest('tr').querySelector('.tag').textContent='Approved';button.closest('tr').querySelector('.tag').classList.remove('pending');showToast('Approval updated and logged.')}));}
function dashboardHtml(){return `<section class="kpi-grid"><article class="kpi-card"><span class="kpi-label">Today's sales</span><div class="kpi-value">₹1,28,450</div><span class="kpi-trend">↗ 8.2% today</span></article><article class="kpi-card"><span class="kpi-label">Diesel sold</span><div class="kpi-value">1,012 L</div><span class="kpi-trend">42 entries</span></article><article class="kpi-card"><span class="kpi-label">Credit sales</span><div class="kpi-value">₹36,700</div><span class="kpi-trend">12 customers</span></article><article class="kpi-card"><span class="kpi-label">Pending approval</span><div class="kpi-value">3</div><span class="kpi-trend">Needs action</span></article></section><section class="dashboard-grid"><article class="panel"><div class="panel-heading"><h2>Sales this week</h2><span>₹8.4L total</span></div><div class="chart">${data.sales.map((value,index)=>`<div class="bar-column"><div class="bar" style="height:${value}%"></div><span>${data.days[index]}</span></div>`).join('')}</div></article><article class="panel"><div class="panel-heading"><h2>Recent activity</h2><span>Updated now</span></div><div class="activity-list">${data.activities.map(([icon,title,sub,status])=>`<div class="activity"><div class="activity-icon">${icon}</div><div><strong>${title}</strong><small>${sub}</small></div><span class="activity-status">${status}</span></div>`).join('')}</div></article></section><section class="panel table-panel"><div class="panel-heading"><h2>Shift snapshot</h2><button class="secondary-button" data-page="reports">View report ↗</button></div><table class="data-table"><thead><tr><th>Shift</th><th>Attendant</th><th>Volume</th><th>Collection</th><th>Status</th></tr></thead><tbody><tr><td>Morning / Pump 01</td><td>R. Karthik</td><td>486 L</td><td>₹61,200</td><td><span class="tag">Closed</span></td></tr><tr><td>Afternoon / Pump 03</td><td>S. Meena</td><td>526 L</td><td>₹67,250</td><td><span class="tag pending">Live</span></td></tr></tbody></table></section>`}
function approvalsHtml(){return `<section class="panel table-panel"><div class="panel-heading"><h2>Needs your attention</h2><span>3 pending</span></div><table class="data-table"><thead><tr><th>Request</th><th>Details</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>${data.approvals.map(([request,detail,amount,status])=>`<tr><td><strong>${request}</strong></td><td>${detail}</td><td>${amount}</td><td><span class="tag ${status==='Pending'?'pending':''}">${status}</span></td><td>${status==='Pending'?'<button class="secondary-button action-approve">Approve</button>':'—'}</td></tr>`).join('')}</tbody></table></section>`}
function accessHtml(){const cards=[['Super Admin','Everything in the workspace',['All modules','Manage users','Audit trail']],['Sales Manager','Runs daily sales and approvals',['Dashboard','Fuel entry','Approvals','Reports']],['Pump Attendant','Records station activity',['Fuel entry','Shift close']],['Accountant','Reconciles money and credit',['Approvals','Customers','Reports']]];return `<section class="role-grid">${cards.map(([name,description,permissions])=>`<article class="role-card"><span class="eyebrow">ROLE</span><h3>${name}</h3><p>${description}</p><div class="permission-list">${permissions.map(permission=>`<span class="permission">${permission}</span>`).join('')}</div></article>`).join('')}</section><section class="panel table-panel"><div class="panel-heading"><h2>Active team</h2><button class="primary-button" id="inviteButton">+ Invite member</button></div><table class="data-table"><thead><tr><th>Member</th><th>Role</th><th>Last active</th><th>Access</th></tr></thead><tbody><tr><td><strong>Arun Kumar</strong></td><td>Super Admin</td><td>Just now</td><td><span class="tag">Full access</span></td></tr><tr><td><strong>Meena S.</strong></td><td>Sales Manager</td><td>12 min ago</td><td><span class="tag">Assigned</span></td></tr><tr><td><strong>Karthik R.</strong></td><td>Pump Attendant</td><td>28 min ago</td><td><span class="tag">Assigned</span></td></tr></tbody></table></section>`}
function customersHtml(){return `<section class="kpi-grid"><article class="kpi-card"><span class="kpi-label">Active accounts</span><div class="kpi-value">28</div><span class="kpi-trend">4 added this month</span></article><article class="kpi-card"><span class="kpi-label">Outstanding credit</span><div class="kpi-value">₹2.8L</div><span class="kpi-trend">↓ 3.4% this week</span></article></section><section class="panel table-panel"><div class="panel-heading"><h2>Customer accounts</h2><button class="primary-button" id="customerButton">+ Add customer</button></div><table class="data-table"><thead><tr><th>Account</th><th>Contact</th><th>Credit limit</th><th>Outstanding</th><th>Status</th></tr></thead><tbody><tr><td><strong>ABC Transport</strong></td><td>94432 18012</td><td>₹1,00,000</td><td>₹36,700</td><td><span class="tag">In good standing</span></td></tr><tr><td><strong>Selvam Earth Movers</strong></td><td>98421 77102</td><td>₹75,000</td><td>₹18,400</td><td><span class="tag">In good standing</span></td></tr></tbody></table></section>`}
function reportsHtml(){return `<section class="kpi-grid"><article class="kpi-card"><span class="kpi-label">Gross sales · this month</span><div class="kpi-value">₹34.6L</div><span class="kpi-trend">↗ 12.8% vs last month</span></article><article class="kpi-card"><span class="kpi-label">Reconciliation</span><div class="kpi-value">99.2%</div><span class="kpi-trend">↑ 0.8% accuracy</span></article><article class="kpi-card"><span class="kpi-label">Total volume</span><div class="kpi-value">26,840 L</div><span class="kpi-trend">32 active shifts</span></article></section><section class="panel empty-panel"><div class="empty-icon">▤</div><h2>Reports are ready to export</h2><p>Choose a date range and download a detailed station report.</p><button class="primary-button" id="exportButton">Export monthly report ↗</button></section>`}
function fuelHtml(){return `<section class="panel empty-panel"><div class="empty-icon">＋</div><h2>Record a fuel movement</h2><p>Keep every sale, issue, and shift close in one place.</p><button class="primary-button" id="pageEntryButton">Open entry form ↗</button></section>`}
function openModal(){$('#entryModal').classList.remove('hidden')}
function closeModal(){$('#entryModal').classList.add('hidden')}
document.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',closeModal));$('#entryModal').addEventListener('click',event=>{if(event.target.id==='entryModal')closeModal()});$('#entryForm').addEventListener('submit',event=>{event.preventDefault();closeModal();showToast('Fuel entry saved to today\'s shift.')});$('#mobileMenu').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$('#logoutButton').addEventListener('click',()=>{portalView.classList.add('hidden');loginView.classList.remove('hidden');showToast('You have been signed out.')});$('#notificationButton').addEventListener('click',()=>showToast('3 approvals need your attention.'));$('#profileButton').addEventListener('click',()=>{if(activeRole==='superadmin'){activePage='access';renderShell()}else showToast(`${roles[activeRole].label} access is active.`)});function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
